### ISSUE TITLE
drd2.pkl isn't a valid scikit-learn model

### ISSUE THREAD

**Issue by SejeongPark8354** [MolecularAI/Lib-INVENT#2]
First of all, 
Thank you for your wonderful researches in drug generation. 

I run the Lib-INVENT RL2-QSAR + RF.ipynb. 
In the process of input.py with generated JSON file, 
I got the error like below. 

```
  File "/home/sejeong/anaconda3/envs/lib-invent/lib/python3.7/site-packages/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 33, in _load_model
    raise Exception(f"The loaded file {parameters.model_path} isn't a valid scikit-learn model")
Exception: The loaded file /home/sejeong/codes/Lib-INVENT/tutorial/models/DRD2_predictive_model/drd2.pkl isn't a valid scikit-learn model
```

Is there any solutions for this issue? 
Also, I have one more question. 
Can I change the prediction model for scoring with my custom model? (not just scikit-learn based model)
Any help would be greatly appreciated.
Thanks!

**Comment by alfredyewang** [comment]
@SejeongPark8354  Downgrade sklearn to 0.21.3 will solve this problem.

**Comment by patronov** [comment]
@SejeongPark8354 We just recently released REINVENT 3.1 and there is some of the functionalities of LibINVENT integrated. Model training isnt there yet but the Reinforcement Learning is in place. There are tutorials in `REINVENT Community` repo. 
With regards to the custom models, one could implement additional logic for new scoring function components. We have released `reinvent-scoring` so you can implement such component within that repo and create a custom environment that uses it instead of the pip version of `reinvent-scoring`.
Let me know if you need guidance with doing so.

**Comment by SejeongPark8354** [comment]
@alfredyewang Thank you for your solution. After I downgraded sklearn to 0.21.3 according to your solution, I got the error like below. Is there anything I missed? 
```
/home/sejeong/anaconda3/envs/lib-invent/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.21.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "input.py", line 20, in <module>
    manager.run()
  File "/home/sejeong/codes/Lib-INVENT/running_modes/manager.py", line 81, in run
    job()
  File "/home/sejeong/codes/Lib-INVENT/running_modes/manager.py", line 51, in _reinforcement_learning
    reinforcement_learning.run()
  File "/home/sejeong/codes/Lib-INVENT/running_modes/reinforcement_learning/reinforcement_learning.py", line 43, in run
    actor_nlls, critic_nlls, augmented_nlls = self._updating(sampled_sequences, score_summary.total_score)
  File "/home/sejeong/codes/Lib-INVENT/running_modes/reinforcement_learning/reinforcement_learning.py", line 59, in _updating
    actor_nlls, critic_nlls, augmented_nlls = self.learning_strategy.run(scaffold_batch, decorator_batch, score, actor_nlls)
AttributeError: 'NoneType' object has no attribute 'run'
```
@patronov Oh, I see. After I check the version and try it, I'll tell you if I need additional helps.

**Comment by patronov** [comment]
@SejeongPark8354 
Looking at the error message above makes me suspect that there is an issue with your input.json config settings. Can you attach the config file you use as an input? I suspect the name of the learning strategy is misspelled.

**Comment by alfredyewang** [comment]
> @SejeongPark8354 Looking at the error message above makes me suspect that there is an issue with your input.json config settings. Can you attach the config file you use as an input? I suspect the name of the learning strategy is misspelled. The valid ones are: DAP = "dap" MAULI = "mauli" MASCOF = "mascof" SDAP = "sdap"

Thank you! Changing 'DAP' to 'dap' will solve the issue.

**Comment by SejeongPark8354** [comment]
@patronov @alfredyewang Oh I see. I used the default setting and didn't realize the misspelling. Thank you!!
